CREATE TABLE IF NOT EXISTS ACCOUNT(
ID INTEGER PRIMARY KEY,
USERNAME CHAR(50),
M5A CHAR(255)
);
CREATE TABLE IF NOT EXISTS CREDENZIALE(
ACCOUNT_ID INTEGER PRIMARY KEY,
M5A CHAR (255),
SITO CHAR(255),
MAIL CHAR(100),
DATA DATE,
FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);

