CREATE DATABASE IF NOT EXISTS PM;
CREATE TABLE IF NOT EXISTS ACCOUNT(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    MAIL CHAR(50),
    SHA3 CHAR(255),
    SALT CHAR(255)
);
CREATE TABLE IF NOT EXISTS CREDENZIALE(
    ID INTEGER PRIMARY KEY,
    ACCOUNT_ID INTEGER,
    PASSWORD CHAR (255),
    SITO CHAR(255),
    MAIL CHAR(100),
    DATA DATETIME,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);
CREATE TABLE IF NOT EXISTS SESSIONE(
    ID_SESSIONE CHAR(50) PRIMARY KEY,
    ACCOUNT_ID INTEGER,
    DATA_INIZIO DATETIME,
    TIMEOUT INTEGER,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);
CREATE TABLE IF NOT EXISTS VERIFICA(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DATA_RICHIESTA DATETIME,
    MAIL CHAR(255),
    SHA3 CHAR(255),
    SALT CHAR(255),
);